### ISSUE TITLE
Polyfill: Regex Parsing :Host Incorrectly

### ISSUE THREAD

**Issue by KirilMK** [ryansolid/component-register#1]
Polyfill not properly parsing :host styling.

Input:
```
:host(.light)
  ::slotted(a:active)
    color:#1a1a1a
```
Output:
`:host(.light) example_component slot > a:active{color:#1a1a1a;}`

**Comment by ryansolid** [comment]
Thanks, it was processing slotted/host/host-context mutually exclusively. Now slotted will be processed independent of the host selectors.
