### ISSUE TITLE
I am not able to render children of custom component conditionally

### ISSUE THREAD

**Issue by karannakra** [ryansolid/component-register#11]
![image](https://user-images.githubusercontent.com/47587853/190508186-e17a5ef2-e8b6-4bea-96b9-4b4b192bf7fd.png)

Is there any way that will alow me to render inner custom component once the condition of outer custom component is resolved ?

**Comment by ryansolid** [comment]
Not really, that's just how web components work. They always eagerly evaluate. The "trick" is to use template elements and then write imperative code to insert the HTML. But it is pretty clunky. This is very high up on my list of where non-web component solutions can be much nicer.

**Comment by karannakra** [comment]
Can you tell me which template elements are you talking about?

**Comment by karannakra** [comment]
In normal webcomponents tags written insdie the custom components are not respected till we use slots correct me if i am wrong?

**Comment by ryansolid** [comment]
Even if you don't put the slots in the light DOM gets evaluated. THey just don't get put in the elements Shadow DOM. The only way to have them not evaluate is to use the template element `<template>`. Maybe on a `slotchange` event. But then you need to imperatively get the reference and clone in the nodes. It's pretty awkward. Some libraries used `<template>` elements with native builtin overrides to do control flow. This is what Polymer used to do. But it is also a bit awkward. https://stackoverflow.com/questions/22974366/polymer-how-to-loop-and-render-html-to-screen
There is no standard way to do this.

**Comment by karannakra** [comment]
This would become pretty combersome

**Comment by ryansolid** [comment]
Yeah webcomponents are sort of poor for this reason. Sometimes pre-emptive child render isn't acceptable. So there isn't really much choice here
