### ISSUE TITLE
Question: how to react to slot change?

### ISSUE THREAD

**Issue by zhaoyao91** [ryansolid/component-register#3]

**Comment by ryansolid** [comment]
I don't have anything specific here. This library just packages up Web Component standards. The different implementations could be worked to do something here but I haven't done anything specific. From a library perspective each Web Component is a separate Island. So the parent passing the children in just bind and react as normal. The Child needs to use Web Component means if they care about that.

So this is probably what you are looking for: https://developer.mozilla.org/en-US/docs/Web/API/HTMLSlotElement/slotchange_event

**Comment by zhaoyao91** [comment]
@ryansolid thanks~
