### ISSUE TITLE
Question: docs about `noShadowDOM`?

### ISSUE THREAD

**Issue by zhaoyao91** [ryansolid/component-register#4]
How to create a custom elements without shadow dom? The readme didn't talk about that. After searching I found there is a `noShadowDOM` function and I tried to call it in the hoc, it seems take effect but I am not sure if it will affect other creations which didn't call it (which should **have** the shadow dom).

**Comment by ryansolid** [comment]
It looks at the current rendering element and updates its renderRoot getter. As long as it is called during the initial render which happens before insert, when it goes to insert it will do into the light dom instead. No other components should be affected.

**Comment by zhaoyao91** [comment]
@ryansolid cool, these would be great to be put into the README or related docs
